### PR TITLE
Issue 484 - Dashboard Pie Chart Constantly Refreshes When Scale Tab Regains Focus (chrome)

### LINKED ISSUE #484: Dashboard Pie Chart Constantly Refreshes When Scale Tab Regains Focus (chrome)
The Running Jobs Pie Chart will refresh upwards of 50+ times when returning the Scale tab from any other browser tab or application. All other charts only refresh once or twice.

Steps to reproduce:
1. Open Scale to the dashboard. Note that the pie chart refreshes twice.
2. Switch to a new tab in the browser or other application altogether.
3. Switch back to the Scale tab. Note that the pie chart refreshes 50+ times before finally stabilizing.

Seen mainly in Chrome 81.0.4044.138
Doesn't appear to happen in Firefox 75.0 (64-bit)
Doesn't appear to happen in Safari 13.1 (15609.1.20.111.8)
Have not tested in Edge

### PR DESCRIPTION
**Pull request by Rachel-ais**
I wasn't able to see that many refreshes locally or on alpha. But I fixed that it was making two calls on init.

Fixes #484

### CODE REVIEW

File: projects/developer/src/app/dashboard/component.ts [hunk 1]
```diff
@@ -106,10 +106,13 @@ export class DashboardComponent implements OnInit, OnDestroy {
         }
     }
     ngOnInit() {
-        this.refreshAllJobTypes();
-        this.jobsService.favoritesUpdated.subscribe(() => {
+        if (this.favoriteJobTypes) {
+            this.jobsService.favoritesUpdated.subscribe(() => {
```
Comment (mheppner) [inline projects/developer/src/app/dashboard/component.ts:110]: Could you also unsubscribe to this? I'm wondering if navigating back and forth to the dashboard is also holding onto these API calls. A pattern I usually do:
- change `this.subscription` into `this.subscriptions = []`
- in `this.unsubscribe()` loop over it, `this.subscriptions.forEach(s => s.unsubscribe()); this.subscriptions = [];`
- anywhere that's a subscription push it into the array, `this.subscriptions.push( this.jobsService.favoritesUpdated.subscribe( ... ) );`

Comment (Rachel-ais) [reply projects/developer/src/app/dashboard/component.ts]: Ok I was able to fix that as well
