### PR TITLE
Issue 481 - recipe status component

### LINKED ISSUE #481: New Recipe Status Component for Dashboard
The Recipe Status Component will provide a way for users to follow their favorite recipes.  The status view will allow users to see the status of a recipe, the status of each pre-determined phase of the recipe, the current/total processing time and include a link to products created.  
Wireframe (note this is an example and should not be taken as end design): 
image
Details:
1. Initially the component will be blank.  A user will need to add their favorite recipes (functionality shown in the prototype in the upper right corner with the + sign)
2. Once a user adds a recipe, they will see a Overall Status, the Name of the Recipe, Recipe phases, the current/total processing time and a link to the products. 

- Overall Status options: Complete/In Progress

- Recipe phases: Data Ingest/Data Parse (if applicable)/Jobs (one dot to represent all jobs with the ability to expand to see details for each job)/Data Created/Data published (if applicable)

- Recipe phase status options: Not started, In Progress, Complete, Failed
not started - all X are pending or queued
in progress - any X are running
complete - all X are complete
failed - any X have failed
Where X is the phase option (exception is data ingest)

- Processing Time: If the recipe is In Progress the time will show how much time has currently passed from beginning to present. If the Recipe Failed or is Complete the Processing Time should show the total time from beginning to complete/failed step. 

- Products will be a link to all products created by that recipe and should be available once the first data product is created from the recipe. This will be a new modal that opens consolidating all the products available from each job. 

- Users can click on Data Parse, Jobs, Data Created and Data published to have a detailed view listing all applicable recipe components and their individual status of Not started/In Progress, Complete or Failed. 

The dashboard will be limited to initially show 10 recipes with a scroll bar if there are more than 10.  Recipes should remain on the board as long as they are In Progress. Recipes should remain on the progress board for 7 days after they have passed- but allow users to delete that recipe from the view if desired.  Recipes should remain on the progress board for 7 days after they have failed- but allow users to restart or delete the recipe instance from the view if desired.

### PR DESCRIPTION
**Pull request by mheppner**
Fixes #481 

Dependent on an API deployed with ngageoint/scale#1894. Please test out if you can, thanks!

### CODE REVIEW

File: projects/developer/src/app/processing/status/component.ts [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+
+@Component({
+    selector: 'dev-processing-status',
+    templateUrl: './component.html',
+    styleUrls: ['./component.scss']
+})
+
+export class ProcessingStatusComponent implements OnInit, OnDestroy {
+    // how often the component should refresh data
+    private static REFRESH_TIME = 10;
```
Comment (emimaesmith) [inline projects/developer/src/app/processing/status/component.ts:19]: After playing with it, the 10 second refresh is a little jarring since it refreshes all items on the page. One moment you're looking at one of the drop downs, the next everything's refreshed. I'm not sure  the best way to resolve this since the point of this component is to always be up to date. Maybe a longer refresh rate would work better?

File: projects/developer/src/app/navbar/navbar.component.ts [hunk 2]
```diff
@@ -99,6 +99,11 @@ export class NavbarComponent implements OnInit, OnChanges, OnDestroy {
                 label: 'Processing',
                 icon: 'fa fa-fw fa-gears',
                 items: [
+                    {
+                        label: 'Status',
```
[the remark this answers is not in the document]
Comment (mheppner) [reply projects/developer/src/app/navbar/navbar.component.ts]: Works for me, changed

File: projects/developer/src/app/processing/status/component.ts (hunk 1 above)
Comment (mheppner) [reply projects/developer/src/app/processing/status/component.ts]: I agree, but wasn't sure how to show it. I could get rid of the loading spinner and just let it transparently update everything? Your other comment above, it only refreshes jobs/sub-recipes if the recipe's `is_completed` is false.
